import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Poppins} from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

const Starshines = localFont({
  src: [
    {
      path: "../fonts/Starshines.otf",
      weight: "1000",
      style: "bold",
    }
  ],
  variable: "--font-Starshines",
});

const Helvetica_Rounded = localFont({
  src: [
    {
      path: "../fonts/helvetica-rounded.otf",
      weight: "700",
      style: "bold",
    }
  ],
  variable: "--font-Helvetica-Rounded",
});

export const metadata: Metadata = {
  title: "Bioplasma 2026",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className={`${Starshines.variable} ${Helvetica_Rounded.variable} ${poppins.variable} min-h-full flex flex-col`} >{children}</body>
    </html>
  );
}
