import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const Starshines = localFont({
  src: [
    {
      path: "../fonts/Starshines.otf",
      weight: "1000",
      style: "bold",
    }
  ],
  variable: "--font-Starshines",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className={`${Starshines.variable} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
